language: java
sudo: enabled
dist: trusty
branches:
  only:
    - master
jobs:
  include:
    - stage: Tests
      script: gradle test -i
    - stage: Release
      if: type != pull_request
      script:
        - eval "$(ssh-agent -s)"
        - cat $GITHUB_SSH_KEY > .travis/deploy_key.pem
        - chmod 600 .travis/deploy_key.pem
        - ssh-add .travis/deploy_key.pem
        - git remote add release git@github.com:SpringSocialMicrosoft/spring-social-partnercenter.git
        - ./.travis/scripts/travis-release.sh
    - stage: Bintray Upload
      if: type != pull_request
      script: ./.travis/scripts/travis-bintray-upload.sh
