language: java
sudo: enabled
dist: trusty
branches:
  only:
    - master
jobs:
  include:
    - stage: Unit Tests
      script: gradle test -i
    - stage: Release
      if: type != pull_request
      script: ./travis-release
    - stage: Bintray Upload
      if: type != pull_request
      script:
        - 'gradle bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PmavenCentralUser=$MAVEN_USER -PmavenCentralPassword=$MAVEN_PASSWORD; fi'
