language: java
sudo: enabled
dist: trusty
branches:
  only:
  - master
script: "./.travis/scripts/before.sh"
jobs:
  include:
  - stage: Tests
    script: gradle test -i
  - stage: Release
    if: type != pull_request
    script: "./.travis/scripts/travis-release.sh"
  - stage: Bintray Upload
    if: type != pull_request
    script: "./.travis/scripts/travis-bintray-upload.sh"
env:
  global:
  - REPO="git@github.com:SpringSocialMicrosoft/spring-social-partnercenter.git"
  - secure: CLFHlNcuLlb4vVUJ5q9hC51nEKghHXh2YXYw1vsVsNI\+fFNsqWZLJYWc\+HQ90yfS346mqRA\/VhZHvlnwNWAt\+YphVGOBRk2ogwYaHPzaeH9oBv0ihTbUhRQQCTdSAEymH8wXMP1uf\/z3PLVuhL7eCiNeny0zmBjJX89cHFXQAUMOtmudyU\/0S2pAZj2WhfnIceZDgCYBuJOEIlrRzfSlA8OIp0kkCB5TwSeqt97jMDZGX19B4cHi75mMIjJ8y6moMKUqAQ023rbgkx2Swxbk9f\+nEd\/Wv\/ov1AjprfDd9FBlCnCeHmLi4Q8ucNoQ6u5Praq8b\+0jEyZpWMgaqi7OofVt\+uiPTOrp7w5HKgkHxqw3PSQ5ID\+JkEjNgI1ZEypU5oXrxzGXA\/gOijO1L8kE1OiUFXuwI3OStdBkjRjQIm2zm8vcgbZW2z8xTozUNyWNr04utD5zjnKSpHHvExL2fuzyKpWNDuSXlKsm5jUjHFNkciin2e0FElln3Qy1ALrKPDwndj6qM1xmvuxPMN2cHONe\+kilphV2rOfG6dt1iuczW7H7Sinj0T8Z30MSgaKgReVm\/7wI3YazXMaBoxWjwdRwiUjbDwLKZswU\/p5\+WfcGKbr5uBq\/cAGOXk6MDV4lwcLqosNT9HFAr\+WAxEfoCNFe1\/7n8OtMzoOfymTaKXQ=
before_install:
  - openssl aes-256-cbc -k "$secret_password" -in ./.travis/id_rsa_github.enc -out ./.travis/id_rsa_github -d
