language: java
sudo: enabled
dist: trusty
branches:
  only:
    - master
jobs:
  include:
    - stage: Unit Tests
      script: gradle test -i
    - stage: Release
      if: type != pull_request AND (head_branch =~ ^release/minor/.* OR branch =~ ^release/minor/.)
      script: ./.travis/scripts/travis-release.sh
    - stage: Bintray Upload
      if: type != pull_request AND (head_branch =~ ^release/minor/.* OR branch =~ ^release/minor/.)
      script: ./.travis/scripts/travis-bintray-upload.sh
