language: java
sudo: enabled
dist: trusty
branches:
  only:
  - master
script: ./.travis/scripts/before.sh
jobs:
  include:
  - stage: Tests
    script: gradle test -i
  - stage: Release
    if: type != pull_request
    script: "./.travis/scripts/travis-release.sh"
  - stage: Bintray Upload
    if: type != pull_request
    script: "./.travis/scripts/travis-bintray-upload.sh"
env:
  global:
  - REPO="git@github.com:SpringSocialMicrosoft/spring-social-partnercenter.git"
before_install:
  - openssl aes-256-cbc -K "$encrypted_86c7e10d33bb_key" -iv "$encrypted_86c7e10d33bb_iv" -in "$CLI_DIR/id_rsa_github.enc" -out "$CLI_DIR/id_rsa_github" -d
