language: java
sudo: enabled
dist: trusty
branches:
  only:
    - master
jobs:
  include:
    - stage: build
      language: java
      script: gradle check
    - stage: release
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then gradle release -Prelease.disableChecks; fi'
    - stage: Bintray Upload
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then gradle bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY; fi'
