language: java
sudo: enabled
dist: trusty
branches:
  only:
    - master
jobs:
  include:
    - stage: Unit Tests
      script: gradle test -i
    - stage: Release
      if: type != pull_request
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ];
           then
           	if [ "$TRAVIS_PULL_REQUEST_BRANCH" =~ "^release/major/.*" ]
           	then
           		gradle release -Prelease.disableChecks -Prelease.pushTagsOnly -Prelease.customUsername=$GITHUB_USER -Prelease.customPassword=$GITHUB_PASSWORD -Prelease.versionIncrementer=incrementMajor -s;
           	elif [ "$TRAVIS_PULL_REQUEST_BRANCH" =~ "^release/minor/.*" ]
           	then
           		gradle release -Prelease.disableChecks -Prelease.pushTagsOnly -Prelease.customUsername=$GITHUB_USER -Prelease.customPassword=$GITHUB_PASSWORD -Prelease.versionIncrementer=incrementMinor -s;
           	elif [ "$TRAVIS_PULL_REQUEST_BRANCH" =~ "^release/.*" ]
           	then
           		gradle release -Prelease.disableChecks -Prelease.pushTagsOnly -Prelease.customUsername=$GITHUB_USER -Prelease.customPassword=$GITHUB_PASSWORD -Prelease.versionIncrementer=incrementPatch -s;
           	fi
           fi'
    - stage: Bintray Upload
      if: type != pull_request
      script:
        - 'gradle bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PmavenCentralUser=$MAVEN_USER -PmavenCentralPassword=$MAVEN_PASSWORD; fi'
